"""user limit tabel created

Revision ID: 108267c1122f
Revises: 7b31d328b4c9
Create Date: 2023-02-18 16:36:14.497073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '108267c1122f'
down_revision = '7b31d328b4c9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_limit',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('limit_id', sa.UUID(), nullable=True),
    sa.Column('limit_duration', sa.String(), nullable=True),
    sa.Column('limit_total', sa.Integer(), nullable=True),
    sa.Column('limit_balance', sa.Integer(), nullable=True),
    sa.Column('outstanding_balance', sa.Integer(), nullable=True),
    sa.Column('createdat', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updatedat', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['limit_id'], ['m_limit.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('m_limit_user_id_fkey', 'm_limit', type_='foreignkey')
    op.drop_column('m_limit', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('m_limit', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('m_limit_user_id_fkey', 'm_limit', 'user', ['user_id'], ['id'])
    op.drop_table('user_limit')
    # ### end Alembic commands ###
