"""remove payment status and also charges

Revision ID: 118dfcd3d8ff
Revises: 7776ed15ea4c
Create Date: 2023-02-20 04:22:45.087204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '118dfcd3d8ff'
down_revision = '7776ed15ea4c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('loan', 'fine_charges')
    op.drop_column('m_limit', 'late_charge')
    op.drop_column('payment', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('m_limit', sa.Column('late_charge', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('loan', sa.Column('fine_charges', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
