"""loan tabel created

Revision ID: 1d1588924e4d
Revises: 108267c1122f
Create Date: 2023-02-19 07:48:52.759081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d1588924e4d'
down_revision = '108267c1122f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loan',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_limit', sa.UUID(), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('est_end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_payment_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_payment_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('loan_tenur', sa.Integer(), nullable=True),
    sa.Column('fine_charges', sa.Integer(), nullable=True),
    sa.Column('total_loan', sa.Integer(), nullable=True),
    sa.Column('total_paid', sa.Integer(), nullable=True),
    sa.Column('emi_amt', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('createdat', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updatedat', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_limit'], ['user_limit.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('loan')
    # ### end Alembic commands ###
