"""m_limit change coloumn

Revision ID: 7b31d328b4c9
Revises: 98accd7a236b
Create Date: 2023-02-17 05:42:46.453398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b31d328b4c9'
down_revision = '98accd7a236b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('m_limit', sa.Column('limit_duration', sa.String(), nullable=True))
    op.add_column('m_limit', sa.Column('duration_type', sa.String(), nullable=True))
    op.add_column('m_limit', sa.Column('late_charge', sa.Integer(), nullable=True))
    op.drop_constraint('m_limit_email_key', 'm_limit', type_='unique')
    op.drop_column('m_limit', 'email')
    op.drop_column('m_limit', 'identity_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('m_limit', sa.Column('identity_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('m_limit', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_unique_constraint('m_limit_email_key', 'm_limit', ['email'])
    op.drop_column('m_limit', 'late_charge')
    op.drop_column('m_limit', 'duration_type')
    op.drop_column('m_limit', 'limit_duration')
    # ### end Alembic commands ###
